DROP TABLE IF EXISTS WX_DATA;
DROP TABLE IF EXISTS WX_STATS;

CREATE TABLE WX_DATA(
    STATION TEXT NOT NULL,
    DATE TEXT NOT NULL,
    MAX_TEMP REAL NOT NULL,
    MIN_TEMP REAL NOT NULL,
    TOT_PREC REAL NOT NULL,
    UNIQUE (STATION, DATE, MAX_TEMP, MIN_TEMP, TOT_PREC)
);

CREATE TABLE WX_STATS(
    STATION TEXT NOT NULL,
    DATE TEXT NOT NULL,
    AVG_MAX_TEMP REAL,
    AVG_MIN_TEMP REAL,
    ACC_TOT_PREC REAL,
    UNIQUE (STATION, DATE, AVG_MAX_TEMP, AVG_MIN_TEMP, ACC_TOT_PREC)
);